train:
  train: False, #True/false
  batch_size: 128 #128
  learning_rate: 0.001 #0.0001
  reg: 0.0005 #0.0005
  epochs: 10 #10
  steps: [6, 8] #[6, 8]
  warmup: 0 #0
  momentum: 0.9 #0.9

network:
  model: vgg16 
  #model: vgg16

data:
  imbalance: regular # regular or imbalance
  save_best: True

loss:
  loss_type: CE # CE or Focal
